# ~/.bash_logout: executed by bash(1) when login shell exits.

# when leaving the console clear the screen to increase privacy

if [ "$SHLVL" = 1 ]; then
	[ -x /usr/bin/clear_console ] && /usr/bin/clear_console -q

	clr

	echo

	/usr/games/fortune -n 100 | /usr/games/cowsay | /usr/games/lolcat

	echo
fi
